### ISSUE TITLE
Archetype won't run on Tomcat in Eclipse

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dd4t-2-java#36]
The dd4t archetype cannot be run on Tomcat combined with Eclipse Mars. The error shows that the dispatcher-servlet cannot be found. Root cause is that the WEB-INF\classes folder that contains the dispatcher-servlet.xml and other property/config files, is not part of the classpath.

Tested with Tomcat 7 in Eclipse Mars.

**Comment by RaimondKempees** [comment]
For some reason, the dispatcher-servlet.xml file is not loaded on the classpath properly in Eclipse. Note that this works fine on application servers and in other IDEs. 

In any case, the configuration was updated to:

    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>WEB-INF/classes/dispatcher-servlet.xml</param-value>
    </context-param>

**Comment by RaimondKempees** [comment]
Turns out this is an issue with the default Maven plugin in Eclipse. It doesn't create a war file, but just runs from the source directories, which is damn ugly. Luckily there is a better plugin. Add this to the POM of you web app:

            <plugin>
                <groupId>org.apache.tomcat.maven</groupId>
                <artifactId>tomcat7-maven-plugin</artifactId>
                <version>2.1</version>
                <configuration>
                    <path>/</path>
                </configuration>
            </plugin>

Then, simply run a Maven Build configuration with goal: **tomcat7:run-war**
